INSERT INTO tb_cursos(nome) VALUES ('Técnico em Informática')
INSERT INTO tb_cursos(nome) VALUES ('Técnico em Logística')
INSERT INTO tb_cursos(nome) VALUES ('Técnico em Eletrotécnica')
INSERT INTO tb_cursos(nome) VALUES ('Técnico em Mecatrônica')
INSERT INTO tb_cursos(nome) VALUES ('Técnico em Eletromecânica')
INSERT INTO tb_cursos(nome) VALUES ('Técnico em Design de Interiores')
INSERT INTO tb_cursos(nome) VALUES ('Técnico em Desenvolvimento de Sistemas')
INSERT INTO tb_cursos(nome) VALUES ('Técnico em Redes de Computadores')
INSERT INTO tb_cursos(nome) VALUES ('Técnico em Manutenção e Suporte em informática')
INSERT INTO tb_cursos(nome) VALUES ('Técnico em Programação de Jogos Digitais')
INSERT INTO tb_cursos(nome) VALUES ('Técnico em Telecomunicações')

INSERT INTO tb_alunos(CPF, nome, curso_id) VALUES('13455791360', 'Aron Ricardo', 7)
INSERT INTO tb_alunos(CPF, nome, curso_id) VALUES('25357222320', 'Ana Célia', 6)
INSERT INTO tb_alunos(CPF, nome, curso_id) VALUES('03864654440', 'Geraldo de Azevedo', 5)
INSERT INTO tb_alunos(CPF, nome, curso_id) VALUES('03956466268', 'Gilberto Ribeiro', 2)